// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: Director/services.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensajes
type PrepareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Director_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_Director_services_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PrepareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MercenaryId string `protobuf:"bytes,1,opt,name=mercenary_id,json=mercenaryId,proto3" json:"mercenary_id,omitempty"`
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Director_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_Director_services_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareResponse) GetMercenaryId() string {
	if x != nil {
		return x.MercenaryId
	}
	return ""
}

type ChoiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Floor        string `protobuf:"bytes,1,opt,name=floor,proto3" json:"floor,omitempty"`
	Alternatives string `protobuf:"bytes,3,opt,name=alternatives,proto3" json:"alternatives,omitempty"`
}

func (x *ChoiceRequest) Reset() {
	*x = ChoiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceRequest) ProtoMessage() {}

func (x *ChoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Director_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceRequest.ProtoReflect.Descriptor instead.
func (*ChoiceRequest) Descriptor() ([]byte, []int) {
	return file_Director_services_proto_rawDescGZIP(), []int{2}
}

func (x *ChoiceRequest) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

func (x *ChoiceRequest) GetAlternatives() string {
	if x != nil {
		return x.Alternatives
	}
	return ""
}

type ChoiceRecover struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MercenaryId string `protobuf:"bytes,1,opt,name=mercenary_id,json=mercenaryId,proto3" json:"mercenary_id,omitempty"`
	Floor       string `protobuf:"bytes,2,opt,name=floor,proto3" json:"floor,omitempty"`
}

func (x *ChoiceRecover) Reset() {
	*x = ChoiceRecover{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChoiceRecover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceRecover) ProtoMessage() {}

func (x *ChoiceRecover) ProtoReflect() protoreflect.Message {
	mi := &file_Director_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceRecover.ProtoReflect.Descriptor instead.
func (*ChoiceRecover) Descriptor() ([]byte, []int) {
	return file_Director_services_proto_rawDescGZIP(), []int{3}
}

func (x *ChoiceRecover) GetMercenaryId() string {
	if x != nil {
		return x.MercenaryId
	}
	return ""
}

func (x *ChoiceRecover) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

type ChoiceMercenary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MercenaryId string `protobuf:"bytes,1,opt,name=mercenary_id,json=mercenaryId,proto3" json:"mercenary_id,omitempty"`
	Floor       string `protobuf:"bytes,2,opt,name=floor,proto3" json:"floor,omitempty"`
	Choice      string `protobuf:"bytes,3,opt,name=choice,proto3" json:"choice,omitempty"`
}

func (x *ChoiceMercenary) Reset() {
	*x = ChoiceMercenary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_services_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChoiceMercenary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceMercenary) ProtoMessage() {}

func (x *ChoiceMercenary) ProtoReflect() protoreflect.Message {
	mi := &file_Director_services_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceMercenary.ProtoReflect.Descriptor instead.
func (*ChoiceMercenary) Descriptor() ([]byte, []int) {
	return file_Director_services_proto_rawDescGZIP(), []int{4}
}

func (x *ChoiceMercenary) GetMercenaryId() string {
	if x != nil {
		return x.MercenaryId
	}
	return ""
}

func (x *ChoiceMercenary) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

func (x *ChoiceMercenary) GetChoice() string {
	if x != nil {
		return x.Choice
	}
	return ""
}

type EliminationNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MercenaryId string `protobuf:"bytes,1,opt,name=mercenary_id,json=mercenaryId,proto3" json:"mercenary_id,omitempty"`
	Alert       string `protobuf:"bytes,2,opt,name=alert,proto3" json:"alert,omitempty"`
}

func (x *EliminationNotification) Reset() {
	*x = EliminationNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_services_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EliminationNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminationNotification) ProtoMessage() {}

func (x *EliminationNotification) ProtoReflect() protoreflect.Message {
	mi := &file_Director_services_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminationNotification.ProtoReflect.Descriptor instead.
func (*EliminationNotification) Descriptor() ([]byte, []int) {
	return file_Director_services_proto_rawDescGZIP(), []int{5}
}

func (x *EliminationNotification) GetMercenaryId() string {
	if x != nil {
		return x.MercenaryId
	}
	return ""
}

func (x *EliminationNotification) GetAlert() string {
	if x != nil {
		return x.Alert
	}
	return ""
}

type MoneyBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MercenaryId string `protobuf:"bytes,1,opt,name=mercenary_id,json=mercenaryId,proto3" json:"mercenary_id,omitempty"`
	Balance     string `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *MoneyBalance) Reset() {
	*x = MoneyBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_services_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoneyBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyBalance) ProtoMessage() {}

func (x *MoneyBalance) ProtoReflect() protoreflect.Message {
	mi := &file_Director_services_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyBalance.ProtoReflect.Descriptor instead.
func (*MoneyBalance) Descriptor() ([]byte, []int) {
	return file_Director_services_proto_rawDescGZIP(), []int{6}
}

func (x *MoneyBalance) GetMercenaryId() string {
	if x != nil {
		return x.MercenaryId
	}
	return ""
}

func (x *MoneyBalance) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type Confirmation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responde string `protobuf:"bytes,1,opt,name=responde,proto3" json:"responde,omitempty"`
}

func (x *Confirmation) Reset() {
	*x = Confirmation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Director_services_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation) ProtoMessage() {}

func (x *Confirmation) ProtoReflect() protoreflect.Message {
	mi := &file_Director_services_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation.ProtoReflect.Descriptor instead.
func (*Confirmation) Descriptor() ([]byte, []int) {
	return file_Director_services_proto_rawDescGZIP(), []int{7}
}

func (x *Confirmation) GetResponde() string {
	if x != nil {
		return x.Responde
	}
	return ""
}

var File_Director_services_proto protoreflect.FileDescriptor

var file_Director_services_proto_rawDesc = []byte{
	0x0a, 0x17, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22,
	0x28, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x34, 0x0a, 0x0f, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x22,
	0x49, 0x0a, 0x0d, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6c,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x73, 0x22, 0x48, 0x0a, 0x0d, 0x43, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6d,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66,
	0x6c, 0x6f, 0x6f, 0x72, 0x22, 0x62, 0x0a, 0x0f, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x4d, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c,
	0x6f, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x6f, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x22, 0x52, 0x0a, 0x17, 0x45, 0x6c, 0x69, 0x6d,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x22, 0x4b, 0x0a, 0x0c,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x2a, 0x0a, 0x0c, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x64, 0x65, 0x32, 0x8b, 0x01, 0x0a, 0x08, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x40, 0x0a, 0x11, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x14, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x32, 0x91, 0x01, 0x0a, 0x0a, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72,
	0x69, 0x6f, 0x12, 0x3b, 0x0a, 0x0d, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x68, 0x6f, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x12,
	0x46, 0x0a, 0x11, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x6c, 0x69, 0x6d,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x47, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x68, 0x6f, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x1a, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79,
	0x32, 0x81, 0x01, 0x0a, 0x08, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a,
	0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x61, 0x72, 0x79, 0x1a, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x61, 0x72, 0x79, 0x32, 0x4a, 0x0a, 0x08, 0x44, 0x6f, 0x73, 0x68, 0x42, 0x61, 0x6e, 0x6b,
	0x12, 0x3e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x12, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_Director_services_proto_rawDescOnce sync.Once
	file_Director_services_proto_rawDescData = file_Director_services_proto_rawDesc
)

func file_Director_services_proto_rawDescGZIP() []byte {
	file_Director_services_proto_rawDescOnce.Do(func() {
		file_Director_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_Director_services_proto_rawDescData)
	})
	return file_Director_services_proto_rawDescData
}

var file_Director_services_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_Director_services_proto_goTypes = []interface{}{
	(*PrepareRequest)(nil),          // 0: main.PrepareRequest
	(*PrepareResponse)(nil),         // 1: main.PrepareResponse
	(*ChoiceRequest)(nil),           // 2: main.ChoiceRequest
	(*ChoiceRecover)(nil),           // 3: main.ChoiceRecover
	(*ChoiceMercenary)(nil),         // 4: main.ChoiceMercenary
	(*EliminationNotification)(nil), // 5: main.EliminationNotification
	(*MoneyBalance)(nil),            // 6: main.MoneyBalance
	(*Confirmation)(nil),            // 7: main.Confirmation
}
var file_Director_services_proto_depIdxs = []int32{
	0, // 0: main.Director.ReportPrepareness:input_type -> main.PrepareRequest
	0, // 1: main.Director.CheckMoneyBalance:input_type -> main.PrepareRequest
	2, // 2: main.Mercenario.ChooseProcess:input_type -> main.ChoiceRequest
	5, // 3: main.Mercenario.NotifyElimination:input_type -> main.EliminationNotification
	3, // 4: main.DataNode.RequestChoice:input_type -> main.ChoiceRecover
	4, // 5: main.NameNode.StoreChoice:input_type -> main.ChoiceMercenary
	2, // 6: main.NameNode.RecoverChoice:input_type -> main.ChoiceRequest
	1, // 7: main.DoshBank.GetCurrentBalance:input_type -> main.PrepareResponse
	1, // 8: main.Director.ReportPrepareness:output_type -> main.PrepareResponse
	6, // 9: main.Director.CheckMoneyBalance:output_type -> main.MoneyBalance
	4, // 10: main.Mercenario.ChooseProcess:output_type -> main.ChoiceMercenary
	7, // 11: main.Mercenario.NotifyElimination:output_type -> main.Confirmation
	4, // 12: main.DataNode.RequestChoice:output_type -> main.ChoiceMercenary
	7, // 13: main.NameNode.StoreChoice:output_type -> main.Confirmation
	4, // 14: main.NameNode.RecoverChoice:output_type -> main.ChoiceMercenary
	6, // 15: main.DoshBank.GetCurrentBalance:output_type -> main.MoneyBalance
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Director_services_proto_init() }
func file_Director_services_proto_init() {
	if File_Director_services_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Director_services_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_services_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_services_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChoiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_services_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChoiceRecover); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_services_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChoiceMercenary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_services_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EliminationNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_services_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoneyBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Director_services_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Director_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_Director_services_proto_goTypes,
		DependencyIndexes: file_Director_services_proto_depIdxs,
		MessageInfos:      file_Director_services_proto_msgTypes,
	}.Build()
	File_Director_services_proto = out.File
	file_Director_services_proto_rawDesc = nil
	file_Director_services_proto_goTypes = nil
	file_Director_services_proto_depIdxs = nil
}
