// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: Director/services.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Director_ReportPrepareness_FullMethodName = "/main.Director/ReportPrepareness"
	Director_ChooseWeapon_FullMethodName      = "/main.Director/ChooseWeapon"
	Director_ChoosePath_FullMethodName        = "/main.Director/ChoosePath"
	Director_GuessNumber_FullMethodName       = "/main.Director/GuessNumber"
	Director_NotifyElimination_FullMethodName = "/main.Director/NotifyElimination"
	Director_CheckMoneyBalance_FullMethodName = "/main.Director/CheckMoneyBalance"
	Director_StoreChoice_FullMethodName       = "/main.Director/StoreChoice"
)

// DirectorClient is the client API for Director service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DirectorClient interface {
	ReportPrepareness(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
	ChooseWeapon(ctx context.Context, in *ChoiceRequest, opts ...grpc.CallOption) (*ChoiceResponse, error)
	ChoosePath(ctx context.Context, in *ChoiceRequest, opts ...grpc.CallOption) (*ChoiceResponse, error)
	GuessNumber(ctx context.Context, in *ChoiceRequest, opts ...grpc.CallOption) (*Confirmation, error)
	NotifyElimination(ctx context.Context, in *EliminationNotification, opts ...grpc.CallOption) (*Confirmation, error)
	CheckMoneyBalance(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*MoneyBalance, error)
	StoreChoice(ctx context.Context, in *ChoiceResponse, opts ...grpc.CallOption) (*Confirmation, error)
}

type directorClient struct {
	cc grpc.ClientConnInterface
}

func NewDirectorClient(cc grpc.ClientConnInterface) DirectorClient {
	return &directorClient{cc}
}

func (c *directorClient) ReportPrepareness(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, Director_ReportPrepareness_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) ChooseWeapon(ctx context.Context, in *ChoiceRequest, opts ...grpc.CallOption) (*ChoiceResponse, error) {
	out := new(ChoiceResponse)
	err := c.cc.Invoke(ctx, Director_ChooseWeapon_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) ChoosePath(ctx context.Context, in *ChoiceRequest, opts ...grpc.CallOption) (*ChoiceResponse, error) {
	out := new(ChoiceResponse)
	err := c.cc.Invoke(ctx, Director_ChoosePath_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) GuessNumber(ctx context.Context, in *ChoiceRequest, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, Director_GuessNumber_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) NotifyElimination(ctx context.Context, in *EliminationNotification, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, Director_NotifyElimination_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) CheckMoneyBalance(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*MoneyBalance, error) {
	out := new(MoneyBalance)
	err := c.cc.Invoke(ctx, Director_CheckMoneyBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) StoreChoice(ctx context.Context, in *ChoiceResponse, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, Director_StoreChoice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectorServer is the server API for Director service.
// All implementations must embed UnimplementedDirectorServer
// for forward compatibility
type DirectorServer interface {
	ReportPrepareness(context.Context, *PrepareRequest) (*PrepareResponse, error)
	ChooseWeapon(context.Context, *ChoiceRequest) (*ChoiceResponse, error)
	ChoosePath(context.Context, *ChoiceRequest) (*ChoiceResponse, error)
	GuessNumber(context.Context, *ChoiceRequest) (*Confirmation, error)
	NotifyElimination(context.Context, *EliminationNotification) (*Confirmation, error)
	CheckMoneyBalance(context.Context, *PrepareRequest) (*MoneyBalance, error)
	StoreChoice(context.Context, *ChoiceResponse) (*Confirmation, error)
	mustEmbedUnimplementedDirectorServer()
}

// UnimplementedDirectorServer must be embedded to have forward compatible implementations.
type UnimplementedDirectorServer struct {
}

func (UnimplementedDirectorServer) ReportPrepareness(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportPrepareness not implemented")
}
func (UnimplementedDirectorServer) ChooseWeapon(context.Context, *ChoiceRequest) (*ChoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChooseWeapon not implemented")
}
func (UnimplementedDirectorServer) ChoosePath(context.Context, *ChoiceRequest) (*ChoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChoosePath not implemented")
}
func (UnimplementedDirectorServer) GuessNumber(context.Context, *ChoiceRequest) (*Confirmation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GuessNumber not implemented")
}
func (UnimplementedDirectorServer) NotifyElimination(context.Context, *EliminationNotification) (*Confirmation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyElimination not implemented")
}
func (UnimplementedDirectorServer) CheckMoneyBalance(context.Context, *PrepareRequest) (*MoneyBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckMoneyBalance not implemented")
}
func (UnimplementedDirectorServer) StoreChoice(context.Context, *ChoiceResponse) (*Confirmation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreChoice not implemented")
}
func (UnimplementedDirectorServer) mustEmbedUnimplementedDirectorServer() {}

// UnsafeDirectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirectorServer will
// result in compilation errors.
type UnsafeDirectorServer interface {
	mustEmbedUnimplementedDirectorServer()
}

func RegisterDirectorServer(s grpc.ServiceRegistrar, srv DirectorServer) {
	s.RegisterService(&Director_ServiceDesc, srv)
}

func _Director_ReportPrepareness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).ReportPrepareness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Director_ReportPrepareness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).ReportPrepareness(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_ChooseWeapon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).ChooseWeapon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Director_ChooseWeapon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).ChooseWeapon(ctx, req.(*ChoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_ChoosePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).ChoosePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Director_ChoosePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).ChoosePath(ctx, req.(*ChoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_GuessNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).GuessNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Director_GuessNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).GuessNumber(ctx, req.(*ChoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_NotifyElimination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminationNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).NotifyElimination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Director_NotifyElimination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).NotifyElimination(ctx, req.(*EliminationNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_CheckMoneyBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).CheckMoneyBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Director_CheckMoneyBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).CheckMoneyBalance(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_StoreChoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChoiceResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).StoreChoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Director_StoreChoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).StoreChoice(ctx, req.(*ChoiceResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// Director_ServiceDesc is the grpc.ServiceDesc for Director service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Director_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.Director",
	HandlerType: (*DirectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportPrepareness",
			Handler:    _Director_ReportPrepareness_Handler,
		},
		{
			MethodName: "ChooseWeapon",
			Handler:    _Director_ChooseWeapon_Handler,
		},
		{
			MethodName: "ChoosePath",
			Handler:    _Director_ChoosePath_Handler,
		},
		{
			MethodName: "GuessNumber",
			Handler:    _Director_GuessNumber_Handler,
		},
		{
			MethodName: "NotifyElimination",
			Handler:    _Director_NotifyElimination_Handler,
		},
		{
			MethodName: "CheckMoneyBalance",
			Handler:    _Director_CheckMoneyBalance_Handler,
		},
		{
			MethodName: "StoreChoice",
			Handler:    _Director_StoreChoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Director/services.proto",
}

const ()

// MercenarioClient is the client API for Mercenario service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MercenarioClient interface {
}

type mercenarioClient struct {
	cc grpc.ClientConnInterface
}

func NewMercenarioClient(cc grpc.ClientConnInterface) MercenarioClient {
	return &mercenarioClient{cc}
}

// MercenarioServer is the server API for Mercenario service.
// All implementations must embed UnimplementedMercenarioServer
// for forward compatibility
type MercenarioServer interface {
	mustEmbedUnimplementedMercenarioServer()
}

// UnimplementedMercenarioServer must be embedded to have forward compatible implementations.
type UnimplementedMercenarioServer struct {
}

func (UnimplementedMercenarioServer) mustEmbedUnimplementedMercenarioServer() {}

// UnsafeMercenarioServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MercenarioServer will
// result in compilation errors.
type UnsafeMercenarioServer interface {
	mustEmbedUnimplementedMercenarioServer()
}

func RegisterMercenarioServer(s grpc.ServiceRegistrar, srv MercenarioServer) {
	s.RegisterService(&Mercenario_ServiceDesc, srv)
}

// Mercenario_ServiceDesc is the grpc.ServiceDesc for Mercenario service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mercenario_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.Mercenario",
	HandlerType: (*MercenarioServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "Director/services.proto",
}

const (
	NameNode_DistributeDecisions_FullMethodName = "/main.NameNode/DistributeDecisions"
)

// NameNodeClient is the client API for NameNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NameNodeClient interface {
	DistributeDecisions(ctx context.Context, in *ChoiceResponse, opts ...grpc.CallOption) (*Confirmation, error)
}

type nameNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNameNodeClient(cc grpc.ClientConnInterface) NameNodeClient {
	return &nameNodeClient{cc}
}

func (c *nameNodeClient) DistributeDecisions(ctx context.Context, in *ChoiceResponse, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, NameNode_DistributeDecisions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NameNodeServer is the server API for NameNode service.
// All implementations must embed UnimplementedNameNodeServer
// for forward compatibility
type NameNodeServer interface {
	DistributeDecisions(context.Context, *ChoiceResponse) (*Confirmation, error)
	mustEmbedUnimplementedNameNodeServer()
}

// UnimplementedNameNodeServer must be embedded to have forward compatible implementations.
type UnimplementedNameNodeServer struct {
}

func (UnimplementedNameNodeServer) DistributeDecisions(context.Context, *ChoiceResponse) (*Confirmation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistributeDecisions not implemented")
}
func (UnimplementedNameNodeServer) mustEmbedUnimplementedNameNodeServer() {}

// UnsafeNameNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NameNodeServer will
// result in compilation errors.
type UnsafeNameNodeServer interface {
	mustEmbedUnimplementedNameNodeServer()
}

func RegisterNameNodeServer(s grpc.ServiceRegistrar, srv NameNodeServer) {
	s.RegisterService(&NameNode_ServiceDesc, srv)
}

func _NameNode_DistributeDecisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChoiceResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServer).DistributeDecisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameNode_DistributeDecisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServer).DistributeDecisions(ctx, req.(*ChoiceResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// NameNode_ServiceDesc is the grpc.ServiceDesc for NameNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NameNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.NameNode",
	HandlerType: (*NameNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DistributeDecisions",
			Handler:    _NameNode_DistributeDecisions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Director/services.proto",
}

const (
	DoshBank_GetCurrentBalance_FullMethodName = "/main.DoshBank/GetCurrentBalance"
)

// DoshBankClient is the client API for DoshBank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DoshBankClient interface {
	GetCurrentBalance(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*MoneyBalance, error)
}

type doshBankClient struct {
	cc grpc.ClientConnInterface
}

func NewDoshBankClient(cc grpc.ClientConnInterface) DoshBankClient {
	return &doshBankClient{cc}
}

func (c *doshBankClient) GetCurrentBalance(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*MoneyBalance, error) {
	out := new(MoneyBalance)
	err := c.cc.Invoke(ctx, DoshBank_GetCurrentBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoshBankServer is the server API for DoshBank service.
// All implementations must embed UnimplementedDoshBankServer
// for forward compatibility
type DoshBankServer interface {
	GetCurrentBalance(context.Context, *PrepareRequest) (*MoneyBalance, error)
	mustEmbedUnimplementedDoshBankServer()
}

// UnimplementedDoshBankServer must be embedded to have forward compatible implementations.
type UnimplementedDoshBankServer struct {
}

func (UnimplementedDoshBankServer) GetCurrentBalance(context.Context, *PrepareRequest) (*MoneyBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentBalance not implemented")
}
func (UnimplementedDoshBankServer) mustEmbedUnimplementedDoshBankServer() {}

// UnsafeDoshBankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoshBankServer will
// result in compilation errors.
type UnsafeDoshBankServer interface {
	mustEmbedUnimplementedDoshBankServer()
}

func RegisterDoshBankServer(s grpc.ServiceRegistrar, srv DoshBankServer) {
	s.RegisterService(&DoshBank_ServiceDesc, srv)
}

func _DoshBank_GetCurrentBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoshBankServer).GetCurrentBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoshBank_GetCurrentBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoshBankServer).GetCurrentBalance(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoshBank_ServiceDesc is the grpc.ServiceDesc for DoshBank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoshBank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.DoshBank",
	HandlerType: (*DoshBankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentBalance",
			Handler:    _DoshBank_GetCurrentBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Director/services.proto",
}
